name: Docker Image CI

on: [push, workflow_dispatch]
    branches: [ "jkedra" ]

#  pull_request:
#    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          export tag=(date +%y%m%d.%H%M))
          docker build . --file Dockerfile --tag jekyll:$tag
          docker tag jekyll:$tag jkedra/jekyll:$tag
          docker push jkedra/jekyll:$tag

#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: jkedra/jekyll:latest


