# https://docs.docker.com/build/ci/github-actions/
#
name: Docker Image CI

on:
  push:
    branches:
      - jkedra
  workflow_dispatch:

#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          export tag=$(date +%y%m%d.%H%M)
          docker build . --file Dockerfile --tag jekyll:$tag
          docker tag jekyll:$tag jkedra/jekyll:$tag
          docker tag jkedra/jekyll:$tag jkedra/jekyll:latest
          docker push jkedra/jekyll:$tag
          docker push jkedra/jekyll:latest

#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          push: true
#          tags: jkedra/jekyll:latest


